trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DeleteFiles@1
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: 'processed_data.pkl'
  displayName: 'Remove Old Data File'

- script: |
    echo "Installing dependencies..."
    python -m pip install --upgrade pip
    pip install pandas
    echo "Running the data processing script..."
    python my_script.py
    echo "Data processing completed."
  displayName: 'Process Data'

# - task: PublishPipelineArtifact@1
# inputs:
#   targetPath: 'processed_data.pkl' 
#   artifact: 'processed_data'

# - task: PostgreSQL@3 
# inputs:
#   hostname: '$(postgres_server)' 
#   port: '5432'
#   database: '$(postgres_database)' 
#   username: '$(postgres_username)' 
#   password: '$(postgres_password)' 
#   sqlFile: '$(Build.SourcesDirectory)/deployment_script.sql'
#   checkConnectionAfterSetup: true 
